application.js
settings.js

https://github.com/amezin/gnome-shell-extension-ddterm/issues/131

Track system color scheme when available

---

po/fr.po

As asked on https://github.com/ddterm/gnome-shell-extension-ddterm/issues/159#issuecomment-1212372261

FR PO: non-breaking spaces before colons

---

wm.js

Avoid "infinite recursion" if there are 0 monitors

---

po/fr.po
po/ru.po
tcgetpgrp.js
terminalpage.js

When a foreground process is running.
Closes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/4

app: ask for confirmation when closing a tab

---

extension.js

Fixes commit 16a2d8540fd0881a4ebc3d3d462942023a07900f

extension: fix null reference access during disable()

---

po/fr.po

I've put the requested translation and also, if you want, the translation of the short presentation for the app.

fr.po update

---

ddterm/app/application.js
ddterm/app/appwindow.js
ddterm/app/notebook.js
ddterm/app/terminal.js
ddterm/app/terminalpage.js
ddterm/app/terminalsettings.js
ddterm/com.github.amezin.ddterm.desktop.in
test/conftest.py
test/ddterm_fixtures.py
test/shell_dbus_api.py
test/test_application.py

https://github.com/ddterm/gnome-shell-extension-ddterm/issues/96

app: handle command line

---

ddterm/app/application.js
ddterm/app/menus.ui
ddterm/app/terminal.js
ddterm/app/terminalpage.js
ddterm/pref/glade/prefs-shortcuts.ui
schemas/com.github.amezin.ddterm.gschema.xml

Copy the implementation from GNOME Terminal.
https://github.com/ddterm/gnome-shell-extension-ddterm/issues/75

app: implement zoom/font scale

---

ddterm/app/terminal.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/570

app/terminal: apply background opacity on style change

---

ddterm/app/application.js
ddterm/app/appwindow.js
ddterm/app/menus.ui
ddterm/app/notebook.js
ddterm/app/terminalpage.js
ddterm/pref/glade/prefs-shortcuts.ui
schemas/com.github.amezin.ddterm.gschema.xml

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/42

app: two notebooks side by side

---

bin/com.github.amezin.ddterm
ddterm/app/application.js
ddterm/app/appwindow.js
ddterm/app/notebook.js
ddterm/app/terminal.js
ddterm/app/terminalpage.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/80

app: save and restore session state

---

ddterm/app/application.js
ddterm/app/appwindow.js
ddterm/pref/glade/prefs-shortcuts.ui
schemas/com.github.amezin.ddterm.gschema.xml

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/645

app: add "focus other pane" action/shortcut

---

ddterm/app/menus.ui
ddterm/app/terminalpage.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/649

app/terminalpage: add 'Show in File Manager' menu item

---

bin/com.github.amezin.ddterm
do-in-docker.sh
do-in-podman.sh

It doesn't understand `--`.
Probably fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/629

Compatibility with `realpath` from busybox

---

ddterm/shell/notifications.js

API was removed in GNOME 46: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3173
Can't embed scrolling into notifications now, so they can't display long text.
Use a dialog window instead.

Remove custom NotificationBanner subclass, use a dialog instead

---

ddterm/shell/notifications.js
metadata.json.in
test/compose.yaml
test/extension/metadata.json

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/807

Enable GNOME 46 support

---

ddterm/app/resources.js
ddterm/app/tools/dependencies-update.js
ddterm/shell/subprocess.js
ddterm/shell/wlclipboard.js
metadata.legacy.json.in
prefs.legacy.js
test/compose.yaml
test/extension-legacy/metadata.json
tools/translate-esm.js

No Gtk 4 version of Vte is available there
https://github.com/ddterm/gnome-shell-extension-ddterm/issues/652

Drop GNOME 40-42 support

---

ddterm/shell/extension.js
ddterm/shell/panelicon.js
metadata.json.in
tools/translate-esm.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1016

Compatibility with GNOME 47

---

ddterm/app/terminal.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1039
Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1040

app/terminal: reimplement old properties using new "termprop" API (VTE 0.78 compatibility)

---

ddterm/shell/animation.js
ddterm/shell/extension.js
ddterm/shell/meson.build
ddterm/shell/wm.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/954

extension/wm: extract animation code to a dedicated class

---

ddterm/app/appwindow.js
ddterm/app/extensiondbus.js
ddterm/com.github.amezin.ddterm.Extension.xml
ddterm/shell/dbusapi.js
ddterm/shell/extension.js
ddterm/shell/geometry.js
test/test_wm.py

Don't trust Gdk, get the value through D-Bus from the extension

Fix monitor scale detection in mixed-DPI configurations

---

ddterm/shell/extension.js

Don't terminate the app and don't uninstall desktop entry and D-Bus service.
Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1087 for GNOME 44 and later

extension: check if disabled only temporarily

---

ddterm/shell/windowmatch.js

extension/windowmatch: GNOME 48 compatibility

---

ddterm/shell/wlclipboard.js
ddterm/shell/wm.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1210

extension/wm: correctly handle `display.focus_window=null`

---

ddterm/app/application.js
ddterm/pref/tabs.js
ddterm/pref/ui/prefs-tabs.ui
schemas/com.github.amezin.ddterm.gschema.xml

https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1235

Add configuration option for session save&restore

---

data/meson.build
ddterm/shell/extension.js
ddterm/shell/notifications.js
ddterm/shell/panelicon.js

Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1287

extension: use new symbolic icon

---

ddterm/shell/extension.js
ddterm/shell/service.js
ddterm/shell/subprocess.js
ddterm/shell/wm.js
meson.build

Tests are failing, mostly because of disabled x11 session support, but from the user's point of view everything seems to work (mostly).

Initial GNOME 49 support

---

tests/test_app.py

Otherwise, there is a race when terminating and immediately restarting the app.

tests/app: assume app to be running if `HasWindow` is `True`

---

ddterm/app/application.js

This should show the version even if the extension failed to load/enable.
Using the standard interface, instead of a custom ad-hoc one, is also nicer.
However, I'm not sure if I can fully trust GNOME Shell.

app: get extension version from Shell
