- application.js
- appwindow.js
- extension.js
- glade/prefs.ui
- prefs.js
- schemas/com.github.amezin.ddterm.gschema.xml
This is an attempt following the instructions in #29/#30 to add a shortcut that toggles the maximized state
I wanted a method to quickly make the terminal cover the full screen/go back to "half-screen". It should be persistent between F12-presses and between monitors.
When the user presses the shortcut (let's say F11) the screen height is changed to 100% and the original height stored.
If the user presses F11 again, the original height is stored.
On first run if there was an "original height" stored it restores it (and then clean that setting).
One reason for doing it in this way (instead of using for instance `fullscreen`) is resizing after maximizing, which I like doing very much.
I've been using it and seems to work fine. Tested only in Gnome 40 though, but I think I'm not doing …
> Add a shortcut for toggling the maximed status

- glade/prefs.ui
- prefs.js
Since a lot of Gnome Shell users use Gnome Terminal, I think it is useful to sync with the color profile of Gnome Terminal.
https://user-images.githubusercontent.com/7223991/122678837-fec15d80-d21a-11eb-9549-5d9f8ac6eb15.mp4
> Support using colors from gnome terminal 

- application.js
- appwindow.js
- glade/prefs.ui
- schemas/com.github.amezin.ddterm.gschema.xml
Default keybindings for increasing/decreasing size are take from Guake, opacity bindings are unset.
This would close #70.
> Add shortcuts for height and opacity

- metadata.json.in
Tested on a fedora 35 workstation (beta) by editing manually the
metadata file at
`~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/metadata.json`.
The extension seems to be working fine.
- the shell is showing
- the setting windows open
Handful of warnings in the logs when I trigger the shell:
```
$ journalctl -fe /usr/bin/gnome-shell
sept. 29 19:44:44 hostname gnome-shell[1941]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
sept. 29 19:44:44 hostname gnome-shell[1941]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
$ gnome-shell --version
GNOME Shell 41.0
```
Close #77 (if the warning is harmless).
> Add gnome-shell 41.x compatibility

- extension.js
GNOME 42 doesn't have sessionMode.allowExtensions
> Shutdown the app when disabling extension on GNOME 42

- Makefile
- ddterm/com.github.amezin.ddterm.desktop
- ddterm/com.github.amezin.ddterm.service
- ddterm/org.gnome.Shell.Extensions.ddterm.service
- ddterm/shell/extension.js
First, refactor the `DesktopEntry` class into a more generic `InstallableResource` class, that doesn't have pre-defined values for `source_file` and `target_file`, and can be used for both the desktop entry file and the dbus service file.
Then, create an instance of this new class for the dbus file and install it to a subdirectory of the user's runtime directory $XDG_RUNTIME_DIR, where the dbus daemon looks for these files.
If merged, this would solve issue #304.
> dbus activation: add dbus service file

- ddterm/pref/glade/prefs-panel-icon.ui
- ddterm/shell/panelicon.js
- po/fr.po
- po/ru.po
- schemas/com.github.amezin.ddterm.gschema.xml
As discussed in #328, I added a new panel button that includes the functionality of both previously available options (toggle and popup menu). I tested it using a touchpad and a mouse and it worked well on both cases.
I already ran the CI and it is failing at the step "Ensure translations are up to date", which I'm not sure how to fix 😅.
As usual, thanks for developing `ddterm`! 🚀
> panelicon: add option to have both toggle and popup menu

- ddterm/shell/panelicon.js
Refactor `PanelIconToggleAndMenu` to inherit from `PanelIconPopupMenu`, so we can change both panel configuration options that include a menu from a single base class.
> panelicon: remove code redundancy between options

- Makefile
Create the variable `MSGMERGE_FLAGS` and add the flag `--no-fuzzy-matching` to it, so only exact matches are used when updating the .po files. Also move the `-U` flag to the same variable, using its non-abbreviated form `--update` for improved clarity.
> translations: disable msgmerge fuzzy matching

- ddterm/app/appwindow.js
> appwindow: make sure tabs are not focusable

- metadata.json.in
I've been using a locally built version of ddterm on GNOME 44 for a few days without any issues. From commit 4c66de2a194690ff49087ee58c373e1b23516f1f, it looks like you already made sure it is compatible with the latest version of the desktop environment.
I added the "44" tag to the `metadata.json` file. I also removed the "44.beta" tag, since it is obsolete now officially that 44 was officially release.
> metadata.json: add support for GNOME 44

- ddterm/app/terminalpage.js
When trying to run the master version of this extension, I encountered the same issue mentioned in [this comment](https://github.com/ddterm/gnome-shell-extension-ddterm/issues/443#issuecomment-1543526683). Looking at the git blame, this seems to be a leftover from removing rxjs.
> Fix custom-command setting

- Makefile
Without this patch build fails with following error:
```
make: *** No rule to make target 'ddterm/app/icons/*', needed by '.../ddterm@amezin.github.com/ddterm/app/icons/*'.  Stop.
```
> Makefile: Expand wildcard

- do-in-docker.sh
- do-in-podman.sh
Add :z flag to volumes. It's fix permission problems on hosts with SELinux (like Fedora 38)
Add HOME env. It's fix permission problems with creation ~/.npm dir
> fix do-in-docker args

- ddterm/app/terminal.js
app: re-apply font settings on style change
Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/674
> React to "Large Text" accessibility setting

- ddterm/shell/wm.js
Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/576
> extension/wm: call `.make_above()` after window is shown on Wayland

- ddterm/com.github.amezin.ddterm.Extension.xml
- ddterm/shell/dbusapi.js
- ddterm/shell/extension.js
I have some scripts that I mostly only run from the dropdown terminal, and I like them to be able to close the dropdown automatically when they finish. `Toggle` works, but on the rare occasions when I run these scripts from other terminals, I don't want it to _open_ the dropdown. Using `Activate` then `Toggle` is a workaround, but it causes the terminal to flicker when the dropdown is not already active.
This PR exposes the idempotent `Hide` action over the D-Bus API. I think I hit all the spots where the code needed to be updated -- I just grepped `toggle` and `activate` and looked for all the spots where it looked like I needed to wire things up. Apologies if I missed anything; I haven't fully wrapped my head around the extension architecture, so this is mostly a copy-paste job.
I wrote …
> extension: expose Hide action in D-Bus API

- ddterm/shell/wm.js
- test/test_extension.py
It seems to work better, windows aren't flying from one monitor to another anymore.
Tested on bare-metal GNOME 46 (Arch), Debian 12 VM.
I had only one monitor for a long time, so I didn't notice how broken it is.
https://github.com/ddterm/gnome-shell-extension-ddterm/issues/405
> extension/wm: try to improve window positioning and resizing

- ddterm/app/terminal.js
Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1037
> app/terminal: use `TERMPROP_CURRENT_DIRECTORY_URI` when available

- po/cs.po
- po/de.po
- po/el.po
- po/eo.po
- po/es.po
- po/fr.po
- po/it.po
- po/meson.build
- po/nb_NO.po
- po/pl.po
- po/pt.po
- po/ru.po
- po/tr.po
- po/zh_CN.po
Currently, translation files either contain a placeholder:
Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
or no explicit copyright notice at all. I'm trying to make the repository compliant with https://reuse.software/ - it requires explicit per-file copyright notices everywhere.
This PR replaces the placeholder with
Copyright (C) <year of file creation> ddterm contributors
And adds the notice where it's missing. .pot file will be fixed automatically by CI.
On one hand, this doesn't change the license, and all possible copyright holders are still included. On the other hand, to be completely safe I should likely ask all contributors for permission - but it's not feasible, some people just don't respond. So I decided to ask at least those who joined the organization.
> translations: fix copyright notices

- ddterm/app/application.js
- ddterm/app/appwindow.js
Do not delete the session file after successfully restoring it. This has the benefit that we do not loose the session in case of a OS/app crash.
Delete the session file if all tabs are closed (windows destroyed).
Delete the session file in case something goes wrong during restoring the session.
I actually could not make the session restore to fail, if I modified a session file it would just not load it and start with a new tab. But it did not throw  any errors or so, which would delete the file. But I guess it cannot hurt to have that in place anyway.
> app: don't remove session file after loading it

- ddterm/app/notebook.js
- ddterm/app/terminal.js
- ddterm/app/terminalpage.js
- tests/apphook.js
- tests/dbus-interfaces/com.github.amezin.ddterm.Debug.xml
- tests/test_app.py
Don't restart processes that terminated before the session was saved.
Fixes https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1277
> Don't restart terminated processes during session restore

- ddterm/shell/wm.js
https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1190
> extension/wm: force activate the window on Wayland

- .github/workflows/ci.yml
- renovate.json
It's pointless. A lot of packages will be installed or updated from the repositories - so the image doesn't really matter
> ci: don't pin Arch Linux container image

- ddterm/shell/wm.js
Wait until the window is mapped on both X11 and Wayland
Seems to be required because of https://gitlab.gnome.org/GNOME/mutter/-/commit/10e094bab9a66375d5ef96352167867901d5a168
> shell/wm: don't activate hidden window on X11 too

- bin/launcher.js
- ddterm/app/dependencies.js
Will probably fix some weird freezes (where a critical error should've caused quick exit but the app hung instead).
Also reduces the number of lines.
> app/launcher: use `runAsync()`, allow `System.exit()` from app code

- ddterm/shell/extension.js
- ddterm/shell/service.js
- ddterm/shell/subprocess.js
- ddterm/shell/windowmatch.js
When calling `.owns_window()` on a `WaylandClient` with terminated subprocess:
gnome-shell[2299]: meta_wayland_client_owns_window: assertion 'client->subprocess.process_running' failed
Service already tracks subprocess running state, so proxy `.owns_window()` through it.
> extension: pass `Service` instead of `Subprocess` to `WindowMatch`

- AUTHORS
- REUSE.toml
- ddterm/app/about.js
- docs/CONTRIBUTING.md
- meson.build
- package.json
- package.json.license
`package.json` contains more metadata than necessary, so better avoid shipping it in the package.
`AUTHORS` file also supports comments - which is handy for multiple reasons.
https://docs.npmjs.com/cli/v11/configuring-npm/package-json#default-values
> List contributors in `AUTHORS` file instead of `package.json`

- tests/dbus-interfaces/org.gnome.Shell.TestHook.xml
- tests/shellhook.js
- tests/test_wm.py
> tests/wm: wait for `Meta.Display.grab-op-{begin,end}` signals

- meson.build
- stylesheet.css
We load the bundled icon by file name now, so the stylesheet does nothing.
> Remove stylesheet.css
